version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd2025_SQL"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_TOKEN: "vault-blogflow-token"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-blogflow-token"
    cap_add:
      - IPC_LOCK
    networks:
      - app-network
  service-api-gateway:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.APIGateway.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  web-service-auth:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Auth.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
      - vault
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
      - VAULT_TOKEN
      - VAULT_ADDR
    networks:
      - app-network
  web-service-core:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Core.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
      - vault
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
      - VAULT_TOKEN
      - VAULT_ADDR
    networks:
      - app-network
  frontend:
    build:
      context: .\frontend\BlogFlow
      dockerfile: .\Dockerfile
    ports:
      - "3000:80"
volumes:
  sql_data:
networks:
  app-network:
