version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd2025_SQL"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
  service-api-gateway:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.APIGateway.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  web-service-auth:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Auth.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  web-service-core:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Core.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  frontend:
    build:
      context: .\frontend\BlogFlow
      dockerfile: .\Dockerfile
    ports:
      - "3000:80"
volumes:
  sql_data:

networks:
  app-network:
