version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd2025_SQL"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  service-api-gateway:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.APIGateway.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  web-service-auth:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Auth.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
      - service-api-gateway
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  web-service-core:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Core.Services.WebApi\Dockerfile
    depends_on:
      - sqlserver
      - service-api-gateway
      - web-service-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network
  notifications-service:
    build:
      context: .\backend\BlogFlow
      dockerfile: .\BlogFlow.Notifications.Worker\Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker-Dev
    networks:
      - app-network

  frontend:
    build:
      context: .\frontend\BlogFlow
      dockerfile: .\Dockerfile
    ports:
      - "3000:80"
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"        # Interfaz web
      - "5342:5341"      # Ingesta de logs desde Serilog
    volumes:
      - seq_data:/data
    networks:
      - app-network
      
volumes:
  sql_data:
  seq_data:

networks:
  app-network:
